app:
  version: 1.0
  debug: true
  timer: 1 #间隔时间 分钟
dnsPod:
  userAgent: Hao88 DDNS/0.1Alpha(52927295@qq.com) #按照dnspod要求的格式
  tokenId: 468352 #tokenID
  loginToken: ccaf314e8449e222197e8434c6fa7044 #token
  format: json  #格式 ，目前仅支持JSON
  domain: hao88.cloud #域名
  subDomain: open #子域名
