# 使用官方的 golang 镜像作为基础镜像
FROM golang:1.20-alpine AS builder
MAINTAINER hao88
LABEL version="1.0"
LABEL description="dnspod ddns go"
LABEL maintainer="hao88.cloud 52927295@qq.com"
WORKDIR /app
RUN ls -l
COPY . .
RUN go mod download
# Build
#RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-gs-ping
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o runner .
RUN find . -type f ! -name 'runner' ! -name 'config.yml' -delete
# Run
CMD ["./runner"]
# --network bridge
# -v /mnt/disk1/appdata/goddnspod/:/