# 使用官方的 golang 镜像作为基础镜像
FROM golang:1.20-alpine
WORKDIR /app
RUN ls -l
COPY . .
RUN go mod download
# Build
#RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-gs-ping
RUN CGO_ENABLED=0 GOOS=linux go build -o runner .
# Run
CMD ["./runner"]
# --network bridge
# -v /mnt/disk1/appdata/goddnspod/:/